theme = "my-catppuccin"

[editor]
auto-format = false
color-modes = true
completion-timeout = 20
completion-trigger-len = 1
cursorline = true
idle-timeout = 20
popup-border = "all"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer"]

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[keys.normal]
"+" = "format_selections"
0 = "goto_line_start"
"=" = ":format"
A-x = "extend_to_line_bounds"
D = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]
X = "select_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.normal."space"]
"f" = "file_picker_in_current_directory"
"F" = "file_picker"
"w" = ":w"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
