theme = "my-catppuccin"

[editor]
auto-format = false
color-modes = true
completion-timeout = 20
completion-trigger-len = 1
cursorline = true
idle-timeout = 20
popup-border = "all"
true-color = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer"]

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "separator", "version-control", "file-name", "spinner", 
  "file-modification-indicator", "read-only-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = " "

[keys.normal]
"+" = "format_selections"
0 = "goto_line_start"
"=" = ":format"
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
L = ["collapse_selection", "extend_to_line_end"] 
H = ["collapse_selection", "extend_to_line_start"] 
x = ["goto_line_start", "select_mode", "goto_line_end_newline"]
X = ["goto_line_start", "select_mode", "goto_line_end_newline"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"Y" = "yank_joined"

[keys.normal."space"]
"f" = "file_picker_in_current_directory"
"F" = "file_picker"
"w" = ":w"

[keys.select]
X = "select_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
L = "extend_to_line_end"
H = "extend_to_line_start"

[keys.insert]
"C-space" = "completion"
