[[language]]
name = "nix"

[language.indent]
tab-width = 4
unit = "\t"

[[language]]
name = "rust"

[language.indent]
tab-width = 4
unit = "\t"

[[language]]
name = "ruby"

[language.indent]
tab-width = 2
unit = "  "

[[language]]
name = "markdown"

[language.indent]
tab-width = 4
unit = "    "
